### ISSUE TITLE
Multiple bugs identified while testing

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1261]
Just some thing I noticed during a bit of testing I did on the latest removemagiclib branch.
Some of these thing are not related to magiclib so maybe this is something you wanna do when #1258 is done.

**connection tree**

- [ ]  ~~active overlay icon not displayed correctly on mremoteng icon~~ See #1264
- [x]  doubleclick on running connection in tree should bring tab to focus
- [x]  copy hostname on folder causes exception
- [ ] ~~unable to rearrange connections within a folder~~ See #1266

 **DPS**

- [ ] ~~putty panel not fitted into window (you can drag it around like a mdichild)~~ See #1265
- [x] ~~the setting to run the components check on every startup should be an option in the actual settings~~
- [ ] ~~when components check is run at startup the form is somehow wierdly docked which causes strange behavior later on.~~

 **settings**

- [x] single click setting (first two checkboxes under connections)
  - [x] when both are enabled an exception is thrown when clicking a connection in the tree
  - [x] seem to only work after a restart but does not show a prompt
- [x] create empty panel on startup not working
  
 **menu**

- [x] quick connect toolbar shows when connection is already active but doesn't bring it to front when clicked
- [ ] ~~jumping to messages/connection pane from view menu does not show the panes when dockstate is set to autohide~~
- [x] ~~quick connect toolbar initiates connection as soon as the protocol is changed. (throws message wenn hostname is empty and does not allow to change protocol beforehand)~~

 **misc**

- [x] update about page to 2019 (critical!)

## Your Environment

* Version used: Lates RemoveMagicLib branch
* Operating System and version: Windows 10 1809

**Comment by sparerd** [comment]
> the setting to run the components check on every startup should be an option in the actual settings

![image](https://user-images.githubusercontent.com/6999446/50937009-9067f680-1437-11e9-845f-545413291e4a.png)

**Comment by sparerd** [comment]
> single click setting (first two checkboxes under connections)
when both are enabled an exception is thrown when clicking a connection in the tree

I get this exception - same for you?
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'mRemoteNG.UI.Tabs.ConnectionTab' to type 'mRemoteNG.UI.Window.ConnectionWindow'.
  Source=mRemoteNG
  StackTrace:
   at mRemoteNG.Connection.ConnectionInitiator.SwitchToOpenConnection(ConnectionInfo connectionInfo) in D:\Repositories\mRemoteNG\mRemoteV1\Connection\ConnectionInitiator.cs:line 56
   at mRemoteNG.Tree.SwitchToConnectionClickHandler.Execute(ConnectionInfo clickedNode) in D:\Repositories\mRemoteNG\mRemoteV1\Tree\ClickHandlers\SwitchToConnectionClickHandler.cs:line 23
   at mRemoteNG.Tree.TreeNodeCompositeClickHandler.Execute(ConnectionInfo clickedNode) in D:\Repositories\mRemoteNG\mRemoteV1\Tree\ClickHandlers\TreeNodeCompositeClickHandler.cs:line 18
   at mRemoteNG.UI.Controls.ConnectionTree.OnMouse_SingleClick(Object sender, MouseEventArgs mouseEventArgs) in D:\Repositories\mRemoteNG\mRemoteV1\UI\Controls\ConnectionTree\ConnectionTree.cs:line 426
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by farosch** [comment]
yes, thats the same exception I get

**Comment by farosch** [comment]
you're absolutely tight with the components check. no idea how i missed that

**Comment by kmscode** [comment]
I'll take a look at these later if possible, otherwise tomorrow most likely.

**Comment by sparerd** [comment]
> seem to only work after a restart but does not show a prompt

This should be resolved in the latest commits to the branch

**Comment by kmscode** [comment]
>when components check is run at startup the form is somehow wierdly docked which causes strange behavior later on.

Could you clarify? I'm not seeing any issues with this...

>putty panel not fitted into window (you can drag it around like a mdichild)

This has happened in the past without DPS as well... But will review further...

> quick connect toolbar shows when connection is already active but doesn't bring it to front when clicked

Could you clarify? I'm not aware of quick connect keeping connection states. Does this work differently in 1.76.12 or the develop branch?

>jumping to messages/connection pane from view menu does not show the panes when dockstate is set to autohide

Does this work differently in 1.76.12 or the develop branch? I have a feeling that this is working the same way in those builds/branches. The notification panel was already using DPS (for quite some time) and this code wasn't modified off the top of my head...

> quick connect toolbar initiates connection as soon as the protocol is changed. (throws message wenn hostname is empty and does not allow to change protocol beforehand)

This is working as designed and has been this way for some time. In older builds, you would be prompted for the connection type. Reference #197

**Comment by farosch** [comment]
>>when components check is run at startup the form is somehow wierdly docked which causes strange behavior later on.

>Could you clarify? I'm not seeing any issues with this...

![image](https://user-images.githubusercontent.com/22905106/50959648-ba66fa80-14c3-11e9-81f1-9592bfdc88a1.png)
The components page is loaded and docked into DPS, but no tab for it is visible.

****

>>quick connect toolbar shows when connection is already active but doesn't bring it to front when clicked

>Could you clarify? I'm not aware of quick connect keeping connection states. Does this work differently in 1.76.12 or the develop branch?

![2019-01-10_10-10-46](https://user-images.githubusercontent.com/22905106/50958097-32332600-14c0-11e9-8db4-008904475bf1.gif)

****

>>jumping to messages/connection pane from view menu does not show the panes when dockstate is set to autohide

> Does this work differently in 1.76.12 or the develop branch? I have a feeling that this is working the same way in those builds/branches. The notification panel was already using DPS (for quite some time) and this code wasn't modified off the top of my head...

Just checked: It's the same behavior on the develop branch

****

>>quick connect toolbar initiates connection as soon as the protocol is changed. (throws message wenn hostname is empty and does not allow to change protocol beforehand)

> This is working as designed and has been this way for some time. In older builds, you would be prompted for the connection type. Reference #197

Is this really working as designed? I would expect the two parts of the button to behave differently:
![image](https://user-images.githubusercontent.com/22905106/50959116-80492900-14c2-11e9-8331-0eed1d87704e.png)
 - Clicking the left part should start a connection with the protocol that's set
 - Clicking the right part (just the arrow) allows to change protocol without starting the connection afterwards

**Comment by kmscode** [comment]
> The components page is loaded and docked into DPS, but no tab for it is visible.

This is the default behavior, is working as designed and is the same as devlop/1.76.* 
If you were to open a different panel (Help -> About) or a connection, you would see the panel tab.
To change this, Options -> Tabs & Panels -> Check "Always Show panel tabs"

![image](https://user-images.githubusercontent.com/16654335/50973467-f051b200-14b6-11e9-8f01-1ae76a4dfe5d.png)


> quick connect toolbar shows when connection is already active but doesn't bring it to front when clicked

Thanks for the clarification. I was thinking the quick connect text box not the connections drop down...

This was also fixed with commit 2f0550de8ea715267dab7ad886d251485012357d

> jumping to messages/connection pane from view menu does not show the panes when dockstate is set to autohide

Since it's the same in develop (and I have a feeling it's been this way forever), feel free to open a new issue as an enhancement with details on how you would like this to function and we can review accordingly.


> quick connect toolbar initiates connection as soon as the protocol is changed. (throws message wenn hostname is empty and does not allow to change protocol beforehand)

Yes, working as designed. The theory here is to allow for easy keyboard navigation since users likely just typed in a hostname... When typing is complete, tab to the protocol button -> arrow down to the desired protocol -> Enter to connect

Feel free to open a new issue on this one as well if you'd like to see different functionality. We can review this as well.

**Comment by kmscode** [comment]
Opened #1264 for the overlay icon problem

**Comment by kmscode** [comment]
Opened #1265 for the putty problem

**Comment by kmscode** [comment]
closing this issue as all items were addressed (fixed, working as designed or new issues opened for specific items).
